const { body, validationResult } = require("express-validator");
const { query, withTransaction } = require("../config/db");
const response = require("../utils/response");
const { v4: uuidv4 } = require("uuid");
const { hasTable, hasColumn } = require("../services/schemaInfo");
const { resolveOrCreateCustomer } = require("../services/customerLink");
const { resolveAccount, requireAccount } = require("../services/accountResolver");

/**
 * A shipment is priced one of two ways, and which one is used depends on
 * whether the goods were actually weighed:
 *
 *   by weight  weight_kg × price_per_kg
 *   flat       a total typed straight in, for a box of electronics that
 *              nobody is going to put on a scale
 *
 * So none of the three fields can be required on its own. What is required
 * is that the shipment ends up with a price by one route or the other, which
 * is checked below rather than field by field.
 */
const hasPrice = (b) => {
  const flat = parseFloat(b.flat_price);
  if (Number.isFinite(flat) && flat > 0) return true;
  const w = parseFloat(b.weight_kg);
  const r = parseFloat(b.price_per_kg);
  return Number.isFinite(w) && w > 0 && Number.isFinite(r) && r > 0;
};

/**
 * An empty margin box is not zero profit — it means no cost was recorded,
 * which is the old behaviour where a shipment was pure margin. Zero, typed
 * deliberately, means the agency made nothing on it. Collapsing the two
 * would silently rewrite every shipment booked before this field existed.
 */
const profitOrNull = (v) => {
  if (v === undefined || v === null || String(v).trim() === "") return null;
  const num = Number(v);
  return Number.isFinite(num) ? Math.round(num * 100) / 100 : null;
};

/**
 * The margin is quoted the way the price is quoted.
 *
 * A shipment charged per kilo has a per-kilo margin — $3 a kilo of which the
 * agency keeps $1 — and multiplying that by the weight is arithmetic the
 * person at the counter should not have to do. A flat-priced shipment has no
 * weight to multiply, so it takes a lump sum. Both end up in profit_total,
 * which is generated by the database, so the stored margin can never
 * disagree with the numbers it came from.
 */
const marginColumns = (body, pricing) =>
  pricing === "flat"
    ? { profit_per_kg: null, profit_flat: profitOrNull(body.profit_flat ?? body.profit_amount) }
    : { profit_per_kg: profitOrNull(body.profit_per_kg), profit_flat: null };

const cargoValidation = [
  // The agency's margin on the shipment. Optional: a parcel carried on a
  // flight already booked costs nothing, and those keep behaving as before.
  body("profit_per_kg")
    .optional({ nullable: true, checkFalsy: true })
    .isFloat({ min: 0 })
    .withMessage("Profit per kg cannot be negative"),
  body("profit_flat")
    .optional({ nullable: true, checkFalsy: true })
    .isFloat({ min: 0 })
    .withMessage("Profit cannot be negative"),
  // Description is optional — "the blue box" is sometimes all there is.
  body("item_description").optional({ nullable: true }).trim(),
  body("weight_kg")
    .optional({ nullable: true, checkFalsy: true })
    .isFloat({ min: 0 })
    .withMessage("Weight must be a positive number"),
  body("price_per_kg")
    .optional({ nullable: true, checkFalsy: true })
    .isFloat({ min: 0 })
    .withMessage("Price per kg must be a positive number"),
  body("flat_price")
    .optional({ nullable: true, checkFalsy: true })
    .isFloat({ min: 0 })
    .withMessage("Price must be a positive number"),
  body().custom((b) => {
    if (!hasPrice(b))
      throw new Error(
        "Give the shipment a price — either a weight and a rate per kg, or a total price.",
      );
    return true;
  }),
  body("sender_name").trim().notEmpty().withMessage("Sender name is required"),
  body("from_city").trim().notEmpty().withMessage("From city is required"),
  body("receiver_name")
    .trim()
    .notEmpty()
    .withMessage("Receiver name is required"),
  body("to_city").trim().notEmpty().withMessage("To city is required"),
];

// Generate a simple tracking number
const generateTracking = () => {
  const prefix = "CGO";
  const num = Math.floor(100000 + Math.random() * 900000);
  return `${prefix}-${num}`;
};

/**
 * GET /api/cargo
 */
const getCargo = async (req, res, next) => {
  try {
    const {
      page = 1,
      limit = 20,
      search = "",
      cargo_status,
      payment_status,
      from_date,
      to_date,
    } = req.query;

    const offset = (parseInt(page) - 1) * parseInt(limit);
    const params = [req.businessId];
    const conditions = ["c.business_id = $1"];
    let pi = 2;

    if (search) {
      conditions.push(
        `(c.sender_name ILIKE $${pi} OR c.receiver_name ILIKE $${pi} OR c.tracking_number ILIKE $${pi} OR c.item_description ILIKE $${pi})`,
      );
      params.push(`%${search}%`);
      pi++;
    }
    if (cargo_status) {
      conditions.push(`c.cargo_status = $${pi}`);
      params.push(cargo_status);
      pi++;
    }
    if (payment_status) {
      conditions.push(`c.payment_status = $${pi}`);
      params.push(payment_status);
      pi++;
    }
    if (from_date) {
      conditions.push(`c.created_at >= $${pi}`);
      params.push(from_date);
      pi++;
    }
    if (to_date) {
      conditions.push(`c.created_at <= $${pi}`);
      params.push(to_date + " 23:59:59");
      pi++;
    }

    const where = conditions.join(" AND ");

    const [countRes, dataRes] = await Promise.all([
      query(`SELECT COUNT(*) FROM cargo_shipments c WHERE ${where}`, params),
      query(
        `SELECT c.*, u.name AS agent_name FROM cargo_shipments c
         LEFT JOIN users u ON u.id = c.created_by
         WHERE ${where} ORDER BY c.created_at DESC
         LIMIT $${pi} OFFSET $${pi + 1}`,
        [...params, parseInt(limit), offset],
      ),
    ]);

    return response.paginated(
      res,
      dataRes.rows,
      page,
      limit,
      parseInt(countRes.rows[0].count),
    );
  } catch (err) {
    next(err);
  }
};

/**
 * POST /api/cargo
 */
const createCargo = async (req, res, next) => {
  try {
    const errors = validationResult(req);
    if (!errors.isEmpty()) return response.validationError(res, errors.array());

    const {
      item_description,
      weight_kg,
      price_per_kg,
      sender_contact,
      from_city,
      receiver_contact,
      to_city,
      notes,
      amount_paid,
      photo_url,
      flat_price,
      arrived_city,
      arrived_office,
      arrived_phone,
    } = req.body;

    // Force uppercase on names
    const sender_name = req.body.sender_name?.toUpperCase().trim();
    const receiver_name = req.body.receiver_name?.toUpperCase().trim();

    const tracking_number = generateTracking();

    // Whichever pricing route was used. Mirrors the generated column in the
    // database exactly, so the payment status computed here can't disagree
    // with the total stored there.
    const num = (v) => {
      const n = parseFloat(v);
      return Number.isFinite(n) ? n : null;
    };
    const flat = num(flat_price);
    const total =
      flat !== null && flat > 0
        ? flat
        : (num(weight_kg) || 0) * (num(price_per_kg) || 0);
    const paid = parseFloat(amount_paid || 0);
    let paymentStatus = "unpaid";
    if (paid >= total) paymentStatus = "paid";
    else if (paid > 0) paymentStatus = "partial";

    // Which account took the money, resolved before the transaction opens.
    const accountId =
      paid > 0 ? await requireAccount(req.body, req.businessId, null, "payment") : null;
    const trackPayments = await hasTable("cargo_payments");
    const hasProfit = await hasColumn("cargo_shipments", "profit_per_kg");
    const hasCustomer = await hasColumn("cargo_shipments", "customer_id");
    const margin = marginColumns(req.body, flat !== null && flat > 0 ? "flat" : "weight");

    // The sender is the customer. Cargo had no customer at all, so a regular
    // shipper existed only as a name retyped on every parcel — no statement,
    // no history, and no way to put their deposit towards a shipment.
    const finalCustomerId = hasCustomer
      ? await resolveOrCreateCustomer({
          businessId: req.businessId,
          customerId: req.body.customer_id,
          name: sender_name,
          phone: sender_contact,
        })
      : null;

    const shipment = await withTransaction(async (client) => {
      const result = await client.query(
        `INSERT INTO cargo_shipments (
          business_id, created_by, item_description, weight_kg, price_per_kg,
          sender_name, sender_contact, from_city,
          receiver_name, receiver_contact, to_city,
          tracking_number, notes, amount_paid, payment_status, photo_url,
          flat_price, arrived_city, arrived_office, arrived_phone
          ${hasProfit ? ", profit_per_kg, profit_flat" : ""}
          ${hasCustomer ? ", customer_id" : ""}
        ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20${hasProfit ? ",$21,$22" : ""}${hasCustomer ? (hasProfit ? ",$23" : ",$21") : ""})
        RETURNING *`,
        [
          req.businessId,
          req.user.id,
          item_description || null,
          num(weight_kg),
          num(price_per_kg),
          sender_name,
          sender_contact || null,
          from_city,
          receiver_name,
          receiver_contact || null,
          to_city,
          tracking_number,
          notes || null,
          paid,
          paymentStatus,
          photo_url || null,
          flat,
          arrived_city || null,
          arrived_office || null,
          arrived_phone || null,
          ...(hasProfit ? [margin.profit_per_kg, margin.profit_flat] : []),
          ...(hasCustomer ? [finalCustomerId] : []),
        ],
      );

      // Record the collection itself, not just the new total. Without this
      // row the money has no time, no account and no collector, so it can
      // never appear in the ledger.
      if (paid > 0 && trackPayments) {
        await client.query(
          `INSERT INTO cargo_payments
             (business_id, cargo_id, collected_by, amount, method, note, account_id)
           VALUES ($1,$2,$3,$4,$5,'Payment at booking',$6)`,
          [
            req.businessId,
            result.rows[0].id,
            req.user.id,
            paid,
            (req.body.payment_method || "cash").trim() || "cash",
            accountId,
          ],
        );
      }

      return result.rows[0];
    });

    return response.created(res, shipment, "Shipment created successfully");
  } catch (err) {
    next(err);
  }
};

/**
 * GET /api/cargo/:id
 */
const getCargoById = async (req, res, next) => {
  try {
    const result = await query(
      `SELECT c.*, u.name AS agent_name FROM cargo_shipments c
       LEFT JOIN users u ON u.id = c.created_by
       WHERE c.id = $1 AND c.business_id = $2`,
      [req.params.id, req.businessId],
    );
    if (result.rows.length === 0)
      return response.notFound(res, "Shipment not found");
    return response.success(res, result.rows[0]);
  } catch (err) {
    next(err);
  }
};

/**
 * PUT /api/cargo/:id
 */
const updateCargo = async (req, res, next) => {
  try {
    const {
      item_description,
      weight_kg,
      price_per_kg,
      sender_name,
      sender_contact,
      from_city,
      receiver_name,
      receiver_contact,
      to_city,
      notes,
      cargo_status,
      amount_paid,
      photo_url,
      flat_price,
      arrived_city,
      arrived_office,
      arrived_phone,
    } = req.body;

    // Recalculate payment status against whichever pricing route was used.
    const num = (v) => {
      const n = parseFloat(v);
      return Number.isFinite(n) ? n : null;
    };
    const flat = num(flat_price);
    const total =
      flat !== null && flat > 0
        ? flat
        : (num(weight_kg) || 0) * (num(price_per_kg) || 0);
    const paid = parseFloat(amount_paid || 0);
    let paymentStatus = "unpaid";
    if (paid >= total) paymentStatus = "paid";
    else if (paid > 0) paymentStatus = "partial";

    // Resolved inside the transaction below, once the change in what was
    // paid is known — an edit that doesn't touch the money needs no account.
    const trackPayments = await hasTable("cargo_payments");
    const hasProfit = await hasColumn("cargo_shipments", "profit_per_kg");
    const marginTouched =
      req.body.profit_per_kg !== undefined || req.body.profit_flat !== undefined;
    const margin = marginColumns(req.body, flat !== null && flat > 0 ? "flat" : "weight");

    const updated = await withTransaction(async (client) => {
      // Read what was paid before, so the change can be recorded as a
      // movement. Editing the total without a matching row would leave the
      // shipment and the ledger disagreeing, and nothing would reveal it.
      const before = await client.query(
        `SELECT amount_paid FROM cargo_shipments WHERE id=$1 AND business_id=$2`,
        [req.params.id, req.businessId],
      );
      if (before.rows.length === 0) return null;
      const previouslyPaid = Number(before.rows[0].amount_paid) || 0;

      const result = await client.query(
        `UPDATE cargo_shipments SET
          item_description=$1, weight_kg=$2, price_per_kg=$3,
          sender_name=$4, sender_contact=$5, from_city=$6,
          receiver_name=$7, receiver_contact=$8, to_city=$9,
          notes=$10, cargo_status=COALESCE($11::cargo_status, cargo_status),
          amount_paid=$12, payment_status=$13,
          photo_url=$16,
          flat_price=$17,
          arrived_city=$18, arrived_office=$19, arrived_phone=$20,
          ${hasProfit && marginTouched ? "profit_per_kg=$21, profit_flat=$22," : ""}
          -- Stamped the moment it is first marked delivered, and never
          -- overwritten afterwards, so 'arrived on' means what it says even
          -- if the record is edited later.
          arrived_at = CASE
            WHEN $11::cargo_status = 'delivered' AND arrived_at IS NULL THEN NOW()
            WHEN $11::cargo_status IS NOT NULL AND $11::cargo_status <> 'delivered' THEN NULL
            ELSE arrived_at
          END
         WHERE id=$14 AND business_id=$15
         RETURNING *`,
        [
          item_description || null,
          num(weight_kg),
          num(price_per_kg),
          sender_name,
          sender_contact || null,
          from_city,
          receiver_name,
          receiver_contact || null,
          to_city,
          notes || null,
          cargo_status || null,
          paid,
          paymentStatus,
          req.params.id,
          req.businessId,
          photo_url || null,
          flat,
          arrived_city || null,
          arrived_office || null,
          arrived_phone || null,
          ...(hasProfit && marginTouched
            ? [margin.profit_per_kg, margin.profit_flat]
            : []),
        ],
      );
      if (result.rows.length === 0) return null;

      // Only the difference is a new movement. A negative one is a refund or
      // a correction — both are real events and both belong in the ledger.
      const delta = Math.round((paid - previouslyPaid) * 100) / 100;
      if (Math.abs(delta) > 0.001 && trackPayments) {
        await client.query(
          `INSERT INTO cargo_payments
             (business_id, cargo_id, collected_by, amount, method, note, account_id)
           VALUES ($1,$2,$3,$4,$5,$6,$7)`,
          [
            req.businessId,
            req.params.id,
            req.user.id,
            delta,
            (req.body.payment_method || "cash").trim() || "cash",
            delta > 0 ? "Further payment" : "Correction or refund",
            await requireAccount(req.body, req.businessId, client, "adjustment"),
          ],
        );
      }

      return result.rows[0];
    });

    if (!updated) return response.notFound(res, "Shipment not found");
    return response.success(res, updated, "Shipment updated");
  } catch (err) {
    next(err);
  }
};

/**
 * DELETE /api/cargo/:id
 */
const deleteCargo = async (req, res, next) => {
  try {
    const result = await query(
      `DELETE FROM cargo_shipments WHERE id = $1 AND business_id = $2 RETURNING id`,
      [req.params.id, req.businessId],
    );
    if (result.rows.length === 0)
      return response.notFound(res, "Shipment not found");
    return response.success(res, null, "Shipment deleted");
  } catch (err) {
    next(err);
  }
};

/**
 * POST /api/cargo/photo
 * Upload (or camera-capture) a single item photo. Returns the stored path;
 * the caller saves it on the shipment as photo_url.
 */
const uploadCargoPhoto = async (req, res, next) => {
  try {
    if (!req.file) return response.error(res, "No photo uploaded", 400);
    if (!req.file.mimetype.startsWith("image/")) {
      return response.error(res, "Only image files are allowed", 415);
    }
    const url = `${req.user.business_id}/${req.file.filename}`;
    return response.created(res, { photo_url: url }, "Photo uploaded");
  } catch (err) {
    next(err);
  }
};

/**
 * DELETE /api/cargo/:id/photo
 */
const deleteCargoPhoto = async (req, res, next) => {
  try {
    const result = await query(
      `UPDATE cargo_shipments SET photo_url = NULL
       WHERE id = $1 AND business_id = $2 RETURNING *`,
      [req.params.id, req.businessId],
    );
    if (result.rows.length === 0)
      return response.notFound(res, "Shipment not found");
    return response.success(res, result.rows[0], "Photo removed");
  } catch (err) {
    next(err);
  }
};

/**
 * POST /api/cargo/:id/payments
 *
 * Take money against a shipment that still owes something, the same way
 * tickets, visas and packages work. Previously the only way to record a
 * further cargo payment was to edit the shipment and change the total paid,
 * which is a different thing entirely — an edit, not a receipt.
 */
const addCargoPayment = async (req, res, next) => {
  try {
    const amount = Math.round((Number(req.body.amount) || 0) * 100) / 100;
    if (amount <= 0) return response.error(res, "Enter a valid amount", 400);

    const found = await query(
      `SELECT id, sender_name, total_price, amount_paid
         FROM cargo_shipments WHERE id = $1 AND business_id = $2`,
      [req.params.id, req.businessId],
    );
    if (found.rows.length === 0)
      return response.notFound(res, "Shipment not found");

    const cargo = found.rows[0];
    const balance =
      Math.round(
        (Number(cargo.total_price) - Number(cargo.amount_paid)) * 100,
      ) / 100;

    if (amount > balance + 0.001)
      return response.error(
        res,
        `Amount exceeds the remaining balance ($${balance.toFixed(2)})`,
        400,
      );

    const accountId = await requireAccount(
      req.body,
      req.businessId,
      null,
      "payment",
    );
    const trackPayments = await hasTable("cargo_payments");

    const updated = await withTransaction(async (client) => {
      if (trackPayments) {
        await client.query(
          `INSERT INTO cargo_payments
             (business_id, cargo_id, collected_by, amount, method, note, account_id)
           VALUES ($1,$2,$3,$4,$5,$6,$7)`,
          [
            req.businessId,
            cargo.id,
            req.user.id,
            amount,
            (req.body.method || "cash").trim() || "cash",
            req.body.note || null,
            accountId,
          ],
        );
      }

      const newPaid = Math.round((Number(cargo.amount_paid) + amount) * 100) / 100;
      const status =
        newPaid >= Number(cargo.total_price) - 0.001
          ? "paid"
          : newPaid > 0
            ? "partial"
            : "unpaid";

      const r = await client.query(
        `UPDATE cargo_shipments
            SET amount_paid = $1, payment_status = $2::payment_status
          WHERE id = $3 AND business_id = $4
          RETURNING *`,
        [newPaid, status, cargo.id, req.businessId],
      );
      return r.rows[0];
    });

    return response.success(
      res,
      updated,
      `$${amount.toFixed(2)} collected from ${cargo.sender_name}`,
    );
  } catch (err) {
    next(err);
  }
};

/**
 * GET /api/cargo/:id/payments
 *
 * Every collection against one shipment, newest first. The printed receipt
 * lists these under RECEIPTS, so the customer can see each instalment rather
 * than one running total they have to take on trust.
 */
const getCargoPayments = async (req, res, next) => {
  try {
    if (!(await hasTable("cargo_payments"))) return response.success(res, []);

    const rows = await query(
      `SELECT p.id, p.amount, p.method, p.note, p.created_at,
              a.name AS account_name, u.name AS collected_by_name
         FROM cargo_payments p
         LEFT JOIN payment_accounts a ON a.id = p.account_id
         LEFT JOIN users u            ON u.id = p.collected_by
        WHERE p.business_id = $1 AND p.cargo_id = $2
        ORDER BY p.created_at DESC`,
      [req.businessId, req.params.id],
    );

    return response.success(
      res,
      rows.rows.map((r) => ({
        ...r,
        amount: Math.round(Number(r.amount) * 100) / 100,
      })),
    );
  } catch (err) {
    next(err);
  }
};

module.exports = {
  getCargoPayments,
  getCargo,
  createCargo,
  getCargoById,
  updateCargo,
  deleteCargo,
  cargoValidation,
  uploadCargoPhoto,
  deleteCargoPhoto,
  addCargoPayment,
};
